### ISSUE TITLE
clojure code is executed twice.

### ISSUE THREAD

**Issue by PlumpMath** [jasilven/ruply#2]
sh -c "ruply -p 5555 -e '(clj-code)'"

clj-code is executed twice.
Is there a way to run nrepl only once on the server side?
and,
I currently only have a Mac, so I wonder if it will be tested on Windows.
(I want to use it for a company work project.)

https://github.com/eraserhd/rep/issues/11
rep is only run once. But there is no Windows version.

Thanks.

**Comment by jasilven** [comment]
"executed twice"..that seems weird. Is it only happening on Windows? 
I only have Linux and Mac machines, so I haven't tested it on Windows.

**Comment by PlumpMath** [comment]
I solved it by just embedding the whole code.  you are my hero!
